name: cap
description: A simple capitalization tool.
version: 1.0.0
repository: https://github.com/noudzandbergen/cap

environment:
  sdk: ^3.4.4

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
